spring:
  datasource:
    url: jdbc:postgresql://localhost:54326/opic_practice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: dev-secret-key-change-in-production-this-must-be-at-least-256-bits-long
  access-expiration: 900000       # 15분
  refresh-expiration: 1209600000  # 14일

internal:
  api-key: test

password:
  reset:
    code:
      secret: dev-secret-key-change-in-production-this-must-be-at-least-256-bits-long
    session-expire-minutes: 100
    code-expire-minutes: 100
    max-attempts: 100
    resend-cooldown-seconds: 100
    max-resend-count: 100
    block-minutes: 100

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics" # 필요한 것만 명시
        exclude: "env,beans,heapdump"
